#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
export LC_ALL=C.UTF-8
unset QORE_MODULE_DIR QORE_MODULE_DIR_ONLY QORE_INCLUDE_DIR LD_LIBRARY_PATH LD_PRELOAD
# Run away from the source/build tree, using installed modules only.
cp test/*.qtest "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
for test in ./*.qtest; do
    timeout 180 /usr/bin/qore "$test" -v
done
